<?php

namespace App\Presenters;

use Nette;

class BasePresenter extends Nette\Application\UI\Presenter
{
    protected function beforeRender() {
        parent::beforeRender(); // TODO: Change the autogenerated stub
        $this->template->menuActive = strtolower($this->name);

        if ($this->name != 'Login' && $this->getUser()->getRoles()[0] != 1) {
            $this->flashMessage("Pro přístup na tyto stránky se musíš přihlásit", "danger");
            $this->redirect("Login:default");
        }
        /* nastavení hesla
        $this->getUser()->getAuthenticator()->modify("jannovak", "nette");
        $this->getUser()->getAuthenticator()->modify("josefnovak", "nette");
        $this->getUser()->getAuthenticator()->modify("kristynanovakova", "nette");
        */
    }

    public function handleLogOut() {
        $this->getUser()->logout();
        $this->redirect('this');
    }
}
